### ISSUE TITLE
RH-SSO all of the things

### ISSUE THREAD

**Issue by jharmison-redhat** [jharmison-redhat/openshift-devsecops#65]
## We need to demonstrate federated identity as part of the solution

As such, I think a list of action-items would be appropriate. The following is my first swing at what this would look like. None of these changes will work in a vacuum, so a branch dedicated to this task would be appropriate. Additionally, I expect this work to cover more than just this repository - I expect that in some cases the operators themselves will need updated. I intend this to serve as the tracking point for all of the work that will need done and its progress.

Any feedback on action-items and any progress made towards this goal will be updated in this root issue. Comments and discussion are encouraged.

### Action Items

---

- [x] Deploy RH-SSO to serve as the auth source of all users
- [ ] Create necessary resources in Keycloak (credentials/roles/etc)
- [ ] OIDC for OCP
- [ ] OIDC for CRW, instead of standalone
- [ ] OIDC for Gitea
- [ ] OIDC for Nexus
- [ ] OIDC for Sonarqube
- [ ] OIDC for Quay
- [ ] OIDC changes for workshop-spawner
- [ ] Deprecate `devsecops-api` script user creation, update as needed for OIDC flows.

**Comment by andykrohg** [comment]
Have a branch going for this in my fork here: https://github.com/andykrohg/openshift-devsecops/tree/sso

**Comment by jharmison-redhat** [comment]
See https://github.com/RedHatGov/devsecops-workshop-code/issues/5
