### ISSUE TITLE
LetsEncrypt has become confusing for RHPDS users

### ISSUE THREAD

**Issue by jharmison-redhat** [jharmison-redhat/openshift-devsecops#70]
The old LetsEncrypt toggle for Quay specifically was just on whether or not there were AWS keys exported or included. Now it's entirely off of the feature flag toggle, and that makes it confusing for some users who weren't including this toggle in their variables and aren't rebuilding their variable files to match the examples often.

I think that, if LetsEncrypt is on but AWS keys aren't present, we should emit a warning and continue on without LetsEncrypt.

**Comment by andykrohg** [comment]
Your approach seems sounds to me 👍
