### ISSUE TITLE
Extraneous roles should be removed

### ISSUE THREAD

**Issue by jharmison-redhat** [jharmison-redhat/openshift-devsecops#71]
We've been carrying 3scale and SM but I just don't think they're going to make it into this kind of workshop and are better left on their own, in my opinion. I think we should drop the roles, and their toggles, from this repo.

Thoughts - @akochnev @andykrohg @mbach04 ?

**Comment by andykrohg** [comment]
👍

**Comment by mbach04** [comment]
Maybe spin off a repo with misc roles for deploying things to OCP?

**Comment by jharmison-redhat** [comment]
> Maybe spin off a repo with misc roles for deploying things to OCP?

We could have an `openshift-devsecops-archive` that contains archived content, but I don't want another thing to maintain...

**Comment by jharmison-redhat** [comment]
See https://github.com/RedHatGov/devsecops-workshop-code/issues/8
